name: "checkout-and-setup"
description: "Checkout the right branch and optionally setup Java"
inputs:
  java-version:
    description: "Java version to setup"
    default: 17
  cache:
    description: "Java setup cache type"
    default: 'maven'

runs:
  using: composite
  steps:
      - uses: actions/checkout@v3
        with:
          # checkout all commits, as the build result depends on `git describe` equivalent
          # and to be able to determine merge base for GIB
          fetch-depth: 0
          ref: |
            ${{ github.event_name == 'repository_dispatch' &&
                github.event.client_payload.pull_request.head.sha == github.event.client_payload.slash_command.args.named.sha &&
                format('refs/pull/{0}/head', github.event.client_payload.pull_request.number) || '' }}
      - name: Verify args
        shell: bash
        if: github.event_name == 'repository_dispatch' && github.event.client_payload.slash_command.args.named.sha == ''
        run: |
          echo >&2 "Dispatched from a slash command but missing the 'sha' argument"
          exit 1
      - name: Verify commit
        shell: bash
        run: |
          expected=${{ github.event_name == 'repository_dispatch' &&
                github.event.client_payload.pull_request.head.sha || '' }}
          actual=$(git log -1 --format='%H')
          if [ -n "$expected" ] && [ "$actual" != "$expected" ]; then
            echo >&2 "Expected to checkout $expected but got $actual"
            exit 1
          fi
      - name: Fetch base ref to find merge-base for GIB
        shell: bash
        run: .github/bin/git-fetch-base-ref.sh
      - uses: actions/setup-java@v3
        if: ${{ inputs.java-version != '' }}
        with:
          distribution: 'zulu'
          java-version: ${{ inputs.java-version }}
      - name: Cache local Maven repo
        id: cache
        if: ${{ inputs.cache == 'maven' }}
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Configure Problem Matchers
        if: ${{ inputs.java-version != '' }}
        shell: bash
        run: echo "::add-matcher::.github/problem-matcher.json"
