name: ci

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
          cache-dependency-path: |
            block-commits/package-lock.json
      - working-directory: block-commits
        run: npm ci
      - working-directory: block-commits
        run: npm run build --if-present
      - working-directory: block-commits
        run: npm test


